import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["600"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Jasmin Naaz",
  description: "Generated by @Nadeem Ahmad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` scroll-smooth max-w-5xl mx-auto  bg-black/80 text-white ${inter.variable} ${poppins.variable} antialiased`}
      >
        <div className="pt-10">
          <Header />
          <div className="h-[1px] bg-white w-full antialiased mt-5 "></div>
        </div>
        <div className="flex max-w-96 md:max-w-2xl mx-auto justify-center items-center pt-10">
          {children}
        </div>
      </body>
    </html>
  );
}
